web/meter/urls.py
from django.urls import path

from meter.views import (
    MeterView,
    ClearMeterView,
    ExportRecordsView,
    DataView,
    SaveCurrentView,
    ChangeSaveContinuouslyView,
    AllRegistersView,
)

app_name = "meter"

urlpatterns = [
    path("<ipv4:ip>/", MeterView.as_view(), name="detail"),
    path("<ipv4:ip>/registers/", AllRegistersView.as_view(), name="registers"),
    path("<ipv4:ip>/clear/", ClearMeterView.as_view(), name="clear"),
    path("<ipv4:ip>/export/", ExportRecordsView.as_view(), name="export"),
    path("<ipv4:ip>/data/", DataView.as_view(), name="data"),
    path("<ipv4:ip>/save_current/", SaveCurrentView.as_view(), name="save_current"),
    path("<ipv4:ip>/change_save_continuously/", ChangeSaveContinuouslyView.as_view(), name="change_save_continuously"),
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, register_converter, include

from core.convertors import IPv4Converter
from core.views import IndexView

admin.autodiscover()

register_converter(IPv4Converter, "ipv4")

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("meter/", include("meter.urls", namespace="meter")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/meter/models.py
import os
import sys
import traceback
from collections import namedtuple
from enum import IntEnum
from typing import Optional, List

import pymodbus.exceptions
from django.conf import settings
from django.db import models, transaction
from django.template.defaultfilters import floatformat
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import localtime
from django.utils.translation import gettext_lazy as _
from pyvisa.errors import VisaIOError

from am3000_reader.reader import AM3000Reader
from core import client
from gpm8213_reader.reader import GPM8213Reader
from modbus_reader.reader import Reader
from pro1_reader.reader import Pro1Reader
from pro380_reader.reader import Pro380Reader
from vaconnx_reader.reader import VaconNXReader


class Meter(models.Model):

    VOLTAGE_DECIMALS = 1
    CURRENT_DECIMALS = 3
    POWER_DECIMALS = 3
    ENERGY_DECIMALS = 6

    ip = models.GenericIPAddressField(verbose_name=_("IP Address"), protocol="IPv4", unique=True)
    reader_type = models.CharField(
        verbose_name=_("Reader Type"),
        choices=(
            ("am3000", "AMx000"),  # works for both AM3000 and AM1000
            ("pro380", "Pro380"),
            ("pro1", "Pro1"),
            ("vacon_nx", "Vacon NX"),
            ("gpm8213", "GPM 8213"),
        ),
        max_length=10,
    )
    save_continuously = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Meter")
        verbose_name_plural = _("Meters")

    def __str__(self):
        return _("Meter at address {}").format(self.ip)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._reader: Optional[Reader] = None
        self.checked = False

    def get_reader_class(self):
        if self.reader_type == "pro380":
            return Pro380Reader
        elif self.reader_type == "pro1":
            return Pro1Reader
        elif self.reader_type == "am3000":
            return AM3000Reader
        elif self.reader_type == "vacon_nx":
            return VaconNXReader
        elif self.reader_type == "gpm8213":
            return GPM8213Reader
        else:
            raise ValueError(_("Unknown reader type"))

    def get_reader_kwargs(self):
        if self.reader_type == "gpm8213":
            return {"check_format": not GPM8213FormatChecked.objects.filter(meter=self).exists()}
        return {}

    @property
    def reader(self) -> Reader:
        if self._reader is not None:
            return self._reader

        self._reader = self.get_reader_class()(self.ip, **self.get_reader_kwargs())

        return self._reader

    def can_connect(self):
        if os.environ.get("MOCK_READER", "false") == "true":
            return True

        try:
            return self.reader.can_connect()
        except pymodbus.exceptions.ConnectionException:
            return False
        except (OSError, VisaIOError):
            return False

    def read(self, *, permanent=False, raise_exceptions=False):
        try:
            response = self.reader.read()
        except pymodbus.exceptions.ConnectionException:
            if raise_exceptions:
                raise
            print("{}: Can't connect to meter {}".format(timezone.now(), self.ip), file=sys.stderr, flush=True)
            return
        except VisaIOError:
            if raise_exceptions:
                raise
            print("{}: Can't read from meter {}".format(timezone.now(), self.ip), file=sys.stderr, flush=True)
            return
        except Exception as e:
            client.captureException()
            print("{}: {}".format(timezone.now(), e), file=sys.stderr, flush=True)
            if settings.DEBUG:
                print(traceback.format_exc())
            if raise_exceptions:
                raise
            return

        if self.reader_type == "gpm8213" and not self.checked:
            self.checked = True
            GPM8213FormatChecked.objects.create(meter=self, created=timezone.now())

        now = timezone.now()

        record = self.record_class(meter=self, created=now)

        for attribute, value in response.items():
            setattr(record, attribute.name, value)

        with transaction.atomic():
            if permanent:
                record.permanent = True
            else:
                save_continuously = Meter.objects.values("save_continuously").get(pk=self.pk)["save_continuously"]

                if (
                    save_continuously
                    and not self.records.filter(created__gte=now.replace(second=0, microsecond=0)).exists()
                ):
                    self.records.filter(permanent=False).delete()

                    record.permanent = True

            record.save()

        return record

    def get_absolute_url(self):
        return reverse("meter:detail", args=[self.ip])

    def show_serial_number(self):
        return self.reader_type == "pro380"

    def one_phase(self):
        return self.reader_type == "pro1"

    @property
    def records(self):
        if self.reader_type == "vacon_nx":
            return self.vaconnxrecord_set
        if self.reader_type == "gpm8213":
            return self.gpm8213record_set
        return self.record_set

    @property
    def record_class(self):
        if self.reader_type == "vacon_nx":
            return VaconNXRecord
        if self.reader_type == "gpm8213":
            return GPM8213Record
        return Record

    Register = namedtuple("Register", "register identifier value")

    def get_all_register_values(self) -> List[Register]:
        reader = self.reader

        registers = []

        for definition in reader.attributes_enum:  # type: IntEnum
            registers.append(self.Register(definition.value, definition.name, reader.read_attribute(definition)))

        return registers


class BaseRecord(models.Model):
    meter = models.ForeignKey(Meter, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(db_index=True)
    permanent = models.BooleanField(default=False, db_index=True)

    class Meta:
        abstract = True

    def serialize(self):
        raise NotImplementedError


class Record(BaseRecord):

    serial_number = models.CharField(max_length=8)

    l1_voltage = models.FloatField()
    l2_voltage = models.FloatField(null=True)
    l3_voltage = models.FloatField(null=True)
    l1_current = models.FloatField()
    l2_current = models.FloatField(null=True)
    l3_current = models.FloatField(null=True)
    l1_active_power = models.FloatField()
    l2_active_power = models.FloatField(null=True)
    l3_active_power = models.FloatField(null=True)
    total_active_power = models.FloatField()
    total_active_energy = models.FloatField()

    # FOR PRO1
    @property
    def voltage(self):
        return self.l1_voltage

    @voltage.setter
    def voltage(self, x):
        self.l1_voltage = x

    @property
    def current(self):
        return self.l1_current

    @current.setter
    def current(self, x):
        self.l1_current = x

    @property
    def active_power(self):
        return self.l1_active_power

    @active_power.setter
    def active_power(self, x):
        self.l1_active_power = x
        self.total_active_power = x

    @property
    def active_energy(self):
        return self.total_active_energy

    @active_energy.setter
    def active_energy(self, x):
        self.total_active_energy = x

    # END PRO1

    def serialize(self, one_phase=False):
        x = {
            "date": localtime(self.created).strftime("%d. %m. %Y"),
            "time": localtime(self.created).strftime("%H:%M:%S"),
            "serial-number": self.serial_number,
            "l1-voltage": floatformat(self.l1_voltage, Meter.VOLTAGE_DECIMALS),
            "l1-current": floatformat(self.l1_current, Meter.CURRENT_DECIMALS),
            "l1-power": floatformat(self.l1_active_power, Meter.POWER_DECIMALS),
            "total-energy": floatformat(self.total_active_energy, Meter.ENERGY_DECIMALS),
        }

        if not one_phase:
            x.update(
                {
                    "l2-voltage": floatformat(self.l2_voltage, Meter.VOLTAGE_DECIMALS),
                    "l3-voltage": floatformat(self.l3_voltage, Meter.VOLTAGE_DECIMALS),
                    "l2-current": floatformat(self.l2_current, Meter.CURRENT_DECIMALS),
                    "l3-current": floatformat(self.l3_current, Meter.CURRENT_DECIMALS),
                    "l2-power": floatformat(self.l2_active_power, Meter.POWER_DECIMALS),
                    "l3-power": floatformat(self.l3_active_power, Meter.POWER_DECIMALS),
                    "total-power": floatformat(self.total_active_power, Meter.POWER_DECIMALS),
                }
            )

        return x


class VaconNXRecord(BaseRecord):
    motor_torque = models.FloatField()
    motor_power = models.FloatField()
    motor_speed = models.IntegerField()
    freq_out = models.FloatField()
    motor_current = models.FloatField()
    motor_voltage = models.FloatField()
    dc_voltage = models.IntegerField()

    @property
    def voltage_ac(self):
        return floatformat(self.motor_voltage, 1)

    @property
    def current(self):
        return floatformat(self.motor_current, 1)

    @property
    def voltage_dc(self):
        return str(self.dc_voltage)

    @property
    def frequency(self):
        return floatformat(self.freq_out, 2)

    @property
    def speed(self):
        return str(self.motor_speed)

    @property
    def torque(self):
        return floatformat(self.motor_torque, 1)

    @property
    def power(self):
        return floatformat(self.motor_power, 1)

    def serialize(self):
        x = {
            "date": localtime(self.created).strftime("%d. %m. %Y"),
            "time": localtime(self.created).strftime("%H:%M:%S"),
            "voltage-ac": self.voltage_ac,
            "current": self.current,
            "voltage-dc": self.voltage_dc,

web/meter/templates/all_registers.html
{% extends "base.html" %}

{% load i18n meter_tags static %}

{% block content %}
    <div class="container">
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Register</th>
                        <th>Identifier</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                {% for register in registers %}
                    <tr>
                        <td>{{ register.register }}</td>
                        <td>{{ register.identifier }}</td>
                        <td>{{ register.value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="text-center">
            <a href="{{ request.path }}" class="button">
                {% trans "Reload" %}
            </a>
        </div>
    </div>
{% endblock %}

web/meter/templates/gpm8213_meter.html
{% extends "base.html" %}

{% load i18n meter_tags static %}

{% block content %}
    <div class="container">
        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{{ meter.get_reader_type_display }}</strong>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Date" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value date">{{ last_record.created|default_if_none:""|date:"d. m. Y" }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Time" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value time">{{ last_record.created|default_if_none:""|date:"H:i:s" }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Voltage V" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value voltage">
                            {{ last_record.voltage|floatformat:3 }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Current A" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value current">
                            {{ last_record.current|floatformat:5 }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Active Power W" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value active_power">
                            {{ last_record.active_power|floatformat:4 }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "WattHours Wh" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value watt_hours">
                            {{ last_record.watt_hours|floatformat:4 }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "AmperHours Ah" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value ampere_hours">
                            {{ last_record.ampere_hours|floatformat:4 }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Time s" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value measurement_time">
                            {{ last_record.measurement_time|floatformat:0 }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="update-now">
                    <span class="freeze">{% trans "Save current values and stop updating" %}</span>
                    <span class="unfreeze" style="display: none;">{% trans "Start updating again" %}</span>
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="save-values">
                    <span class="activate">{% trans "Save continously" %}</span>
                    <span class="deactivate" style="display: none;">{% trans "Stop saving continously" %}</span>
                </button>
            </div>
        </div>
        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button" id="export">
                    {% trans "Export Data" %}
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button" id="clear-data">
                    {% trans "Clear Data" %}
                </button>
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_js %}
    <script type="text/javascript">
        window.urls = {
            clear_data: "{% url "meter:clear" meter.ip %}",
            export_data: "{% url "meter:export" meter.ip %}",
            data: "{% url "meter:data" meter.ip %}",
            save_current: "{% url "meter:save_current" meter.ip %}",
            change_save_continuously: "{% url "meter:change_save_continuously" meter.ip %}",
        };
        window.save_continuously = {% if meter.save_continuously %}true{% else %}false{% endif %};
    </script>
    <script src="{% static "meter.js" %}" type="text/javascript"></script>
{% endblock %}

web/meter/templates/meter.html
{% extends "base.html" %}

{% load i18n meter_tags static %}

{% block content %}
    <div class="container">
        <div class="row outline-row">
            <div class="column column-25">
                <div class="outline-column">
                    <strong>{{ meter.get_reader_type_display }}</strong>
                </div>
            </div>
            <div class="column column-25">
                <div class="outline-column">
                    <strong>{% trans "Date" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value date">{{ last_record.created|default_if_none:""|date:"d. m. Y" }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-25">
                <div class="outline-column">
                    <strong>{% trans "Time" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value time">{{ last_record.created|default_if_none:""|date:"H:i:s" }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-25">
                {% if meter.show_serial_number %}
                    <div class="outline-column">
                        <strong>{% trans "Serial Number" %}</strong><br>
                        <div class="text-right">
                            <span class="record-value serial-number">{{ last_record.serial_number }}</span>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

        {% for phase in phases %}
            <div class="row outline-row">
                <div class="column column-25">
                    <div class="outline-column">
                        <strong>
                            {% trans "Phase" %} {% if not one_phase %}{{ phase|upper }}{% else %}L{% endif %}
                        </strong>
                    </div>
                </div>
                <div class="column column-25">
                    <div class="outline-column">
                        <strong>{% trans "Voltage V" %}</strong><br>
                        <div class="text-right">
                            <span class="record-value {{ phase }}-voltage">
                                {{ last_record|voltage:phase|floatformat:voltage_decimals }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="column column-25">
                    <div class="outline-column">
                        <strong>{% trans "Current A" %}</strong><br>
                        <div class="text-right">
                            <span class="record-value {{ phase }}-current">
                                {{ last_record|current:phase|floatformat:current_decimals }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="column column-25">
                    <div class="outline-column">
                        <strong>{% trans "Active Power kW" %}</strong><br>
                        <div class="text-right">
                            <span class="record-value {{ phase }}-power">
                                {{ last_record|active_power:phase|floatformat:power_decimals }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="row outline-row">
            {% if not one_phase %}
                <div class="column column-50">
                    <div class="outline-column">
                        <strong>{% trans "Total Active Power kW" %}</strong><br>
                        <div class="text-right">
                            <span class="record-value total-power">
                            {{ last_record.total_active_power|default_if_none:""|floatformat:power_decimals }}
                            </span>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="column {% if not one_phase %}column-50{% endif %}">
                <div class="outline-column">
                    <strong>{% trans "Total Active Energy kWh" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value total-energy">
                            {{ last_record.total_active_energy|default_if_none:""|floatformat:energy_decimals }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="update-now">
                    <span class="freeze">{% trans "Save current values and stop updating" %}</span>
                    <span class="unfreeze" style="display: none;">{% trans "Start updating again" %}</span>
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="save-values">
                    <span class="activate">{% trans "Save continously" %}</span>
                    <span class="deactivate" style="display: none;">{% trans "Stop saving continously" %}</span>
                </button>
            </div>
        </div>
        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button" id="export">
                    {% trans "Export Data" %}
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button" id="clear-data">
                    {% trans "Clear Data" %}
                </button>
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_js %}
    <script type="text/javascript">
        window.urls = {
            clear_data: "{% url "meter:clear" meter.ip %}",
            export_data: "{% url "meter:export" meter.ip %}",
            data: "{% url "meter:data" meter.ip %}",
            save_current: "{% url "meter:save_current" meter.ip %}",
            change_save_continuously: "{% url "meter:change_save_continuously" meter.ip %}",
        };
        window.save_continuously = {% if meter.save_continuously %}true{% else %}false{% endif %};
    </script>
    <script src="{% static "meter.js" %}" type="text/javascript"></script>
{% endblock %}

web/meter/templates/meter_unavailable.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger">
            <p>{% trans "The meter is currently not available." %}</p>
        </div>

        <div class="text-center">
            <a class="button" href="{{ meter.get_absolute_url }}">{% trans "Try again" %}</a>
        </div>
    </div>

{% endblock %}

web/meter/templates/vacon_nx_meter.html
{% extends "meter.html" %}

{% load i18n meter_tags static %}

{% block content %}
    <div class="container">
        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{{ meter.get_reader_type_display }}</strong>
                    <div class="text-right">
                        <span class="record-value ip-address">{{ meter.ip }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Date" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value date">{{ last_record.created|default_if_none:""|date:"d. m. Y" }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Time" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value time">{{ last_record.created|default_if_none:""|date:"H:i:s" }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Voltage AC [V]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value voltage-ac">{{ last_record.voltage_ac }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Current [A]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value current">{{ last_record.current }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Voltage DC [V]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value voltage-dc">{{ last_record.voltage_dc }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Frequency [Hz]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value frequency">{{ last_record.frequency }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row outline-row">
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Speed [rpm]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value speed">{{ last_record.speed }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Torque [%]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value torque">{{ last_record.torque }}</span>
                    </div>
                </div>
            </div>
            <div class="column column-33">
                <div class="outline-column">
                    <strong>{% trans "Power [%]" %}</strong><br>
                    <div class="text-right">
                        <span class="record-value power">{{ last_record.power }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="update-now">
                    <span class="freeze">{% trans "Save current values and stop updating" %}</span>
                    <span class="unfreeze" style="display: none;">{% trans "Start updating again" %}</span>
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button button-outline" id="save-values">
                    <span class="activate">{% trans "Save continously" %}</span>
                    <span class="deactivate" style="display: none;">{% trans "Stop saving continously" %}</span>
                </button>
            </div>
        </div>
        <div class="row">
            <div class="column column-50 text-center">
                <button type="button" class="button" id="export">
                    {% trans "Export Data" %}
                </button>
            </div>
            <div class="column column-50 text-center">
                <button type="button" class="button" id="clear-data">
                    {% trans "Clear Data" %}
                </button>
            </div>
        </div>
    </div>
{% endblock %}